version: "3.9"

services:
  db:
    image: grahamgilbert/postgres
    ports:
      - "5432:5432"
    volumes:
      - /tmp/postgresql/db:/var/lib/postgresql/data
    restart: always
    environment:
      DB_NAME: sal
      DB_USER: admin
      DB_PASS: password

  sal:
    depends_on:
      - db
    image: ghcr.io/aptlogic/sal:latest
    ports:
      - "80:8000"
    restart: always
    environment:
      ADMIN_PASS: pass
      DB_NAME: sal
      DB_USER: admin
      DB_PASS: password
volumes:
  db_data: {}
