version: 2
jobs:
  test:
    docker:
      - image: cimg/python:3.9.16

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pip install -r setup/requirements.txt
            pip install flake8
            cp sal/example_settings.py sal/settings.py
            python manage.py test
            python manage.py migrate
      - run:
          name: run linting
          command: |
            pip install -r setup/requirements.txt
            pip install flake8
            flake8

      - store_artifacts:
          path: test-reports
          destination: test-reports
  build_latest:
    docker:
      - image: docker:20.10.23-git

    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t macadmins/sal:latest .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push macadmins/sal:latest
      - run: pip install requests
      - run: python remote_build.py latest

  build_branch:
    docker:
      - image: docker:20.10.23-git

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t macadmins/sal:${CIRCLE_BRANCH//\//_} .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push macadmins/sal:${CIRCLE_BRANCH//\//_}
      - run: apk update
      - run: pip install requests
      - run: python remote_build.py ${CIRCLE_BRANCH//\//_}

  build_tag:
    docker:
      - image: docker:20.10.23-git

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t macadmins/sal:$CIRCLE_TAG .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push macadmins/sal:$CIRCLE_TAG
      - run: pip install requests
      - run: python remote_build.py $CIRCLE_TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build_latest:
          requires:
            - test
          filters:
            branches:
              only: main
      - build_branch:
          requires:
            - test
          filters:
            branches:
              ignore:
                - main
      - build_tag:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
