# Generated by Django 5.2.7 on 2025-11-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_auto_20190228_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrow',
            name='operator',
            field=models.CharField(choices=[('Contains', 'Contains'), ('=', '='), ('!=', '!='), ('<', '<'), ('<=', '<='), ('>', '>'), ('>=', '>='), ('Starts with', 'Starts with'), ('Ends with', 'Ends with')], default='Contains', max_length=20),
        ),
    ]
