name: Build Latest

on:
  push:
    branches:
      - 'main'

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        push: true
        tags: ghcr.io/salopensource/sal:latest
    
    - name: Build and Push SAML Docker image
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        file: Dockerfile-SAML
        push: true
        tags: ghcr.io/salopensource/sal-saml:latest
