name: Build Latest

on:
  push:
    branches:
      - 'main'

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        tags: ghcr.io/aptlogic/sal:latest
